require 'mappings'
require 'plugins'
require 'settings'
require 'lualine_config'
require 'lspconfig_config'
require 'treesitter_config'
require 'sneak_config'
require('nvim-autopairs').setup {}
require 'telescope_config'
require 'cmp_config'
require 'nvim-tree_config'
require 'tabline_config'
require 'quickscope_config'
require 'nvim-terminal_config'
require 'which-key_config'
require('colorizer').setup {}
require 'neoclip_config'
require('Comment').setup {}
require('lsp_signature').setup {}
require 'highlightedyank_config'
